### ISSUE TITLE
Ao adicionar um novo item, deixar a lógica concentrada na função "addItem"

### ISSUE THREAD

**Issue by GabrielPaliari** [karinafukuda/todolist-angular#1]
https://github.com/karinafukuda/todolist-angular/blob/38bb31cc8629c79ff06510dd455d348fd95e9658/src/app/components/todo-list/todo-list.component.html#L5-L11

Na linha 8, tente deixar tudo dentro da função (retirando a parte depois do ponto e virgula e passando para o arquivo .ts). Para que a lógica fique concentrada em um único lugar, isso faz com que fique mais fácil corrigir bugs. Para isso você pode passar ao invés da descrição, a referência para o campo. Você pode ter dificuldade por conta dos tipos do typescript. Mas dê uma olhada nesse artigo sobre element ref (quando usamos o # no html criamos uma ElementRef): https://ultimatecourses.com/blog/element-refs-in-angular-templates

**Comment by karinafukuda** [comment]
Resolvida
