### ISSUE TITLE
Remover propriedades não utilizadas

### ISSUE THREAD

**Issue by GabrielPaliari** [karinafukuda/todolist-angular#5]
https://github.com/karinafukuda/todolist-angular/blob/fb3680b71ae31c78595ae48b428e5025b96cc48f/src/app/components/count-task/count-task.component.ts#L11-L12

Todo código é importante, se não for, delete. Notei que você não usou algumas propriedades neste componente, pode deletar. Nunca comente, se não for usar, o git dá conta de manter o registro caso você precise.

**Comment by karinafukuda** [comment]
Resolvida
