### ISSUE TITLE
Criar componente de adicionar nova tarefa

### ISSUE THREAD

**Issue by GabrielPaliari** [karinafukuda/todolist-angular#6]
https://github.com/karinafukuda/todolist-angular/blob/017e59288bbe8ad95adb3a87889cad6b573ece69/src/app/components/todo-list/todo-list.component.html#L4-L16

Seria legal componentizar este componente de campo de texto e o botão de adicionar em um componente "AddTask" para ficar com uma arquitetura melhor. Assim o componente pai se responsabiliza apenas por gerenciar o array e não o input de usuárie

**Comment by GabrielPaliari** [comment]
Use Output para passar o dado do componente de adicionar para o componente pai

**Comment by karinafukuda** [comment]
Resolvida
