### ISSUE TITLE
DRY - Dont Repeat Yourself

### ISSUE THREAD

**Issue by GabrielPaliari** [karinafukuda/todolist-angular#7]
https://github.com/karinafukuda/todolist-angular/blob/017e59288bbe8ad95adb3a87889cad6b573ece69/src/app/components/item/item.component.html#L17

https://github.com/karinafukuda/todolist-angular/blob/017e59288bbe8ad95adb3a87889cad6b573ece69/src/app/components/item/item.component.html#L32

Cuidado para não se repetir. Quando perceber isso, crie uma função que encapsule a lógica, por mais que ela seja simples (ela pode mudar e vai ser mais difícil se tiver em vários lugares, podendo até gerar bugs). Pesquise o princípio e origem do acrônimo DRY, uma boa fonte é o livro Clean Code do Bob Martin.

**Comment by karinafukuda** [comment]
Resolvida
