### ISSUE TITLE
Utilizar o dado do evento de output corretamente remove($event)

### ISSUE THREAD

**Issue by GabrielPaliari** [karinafukuda/todolist-angular#8]
https://github.com/karinafukuda/todolist-angular/blob/017e59288bbe8ad95adb3a87889cad6b573ece69/src/app/components/item/item.component.ts#L14 Perceba que aqui voce declarou que este emissor de eventos deveria receber um item
https://github.com/karinafukuda/todolist-angular/blob/017e59288bbe8ad95adb3a87889cad6b573ece69/src/app/components/item/item.component.html#L18 Mas aqui você emitiu o evento vazio, e não utilizou o dado do evento no componente pai. O correto é voce emitir o item e no pai usar o $event para pegar os dados.
https://github.com/karinafukuda/todolist-angular/blob/017e59288bbe8ad95adb3a87889cad6b573ece69/src/app/components/todo-list/todo-list.component.html#L24 Note que você não usou dado nenhum do evento, você apenas usou o item do ng-for. 
Ficaria assim no componente pai:
`<app-item (remove)="remove($event)" [item]="item"></app-item> `
Você pode fazer da forma que você fez, mas fica mais claro desta outra forma dado os tipos que você estabeleceu.

**Comment by karinafukuda** [comment]
Resolvida
