### ISSUE TITLE
Considerações gerais sobre o projeto e de estilo

### ISSUE THREAD

**Issue by GabrielPaliari** [karinafukuda/todolist-angular#9]
1. Interessante que você colocou id para todos os elementos do HTML, mantenha essa prática pois isso facilita os testes. Dê uma olhada na documentação dos data attributes, pois para testes você pode utilizar por exemplo uma propriedade com o nome data-testid e depois remover isso para produção. https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes, https://betterprogramming.pub/decouple-tests-with-data-attributes-c920606c5f27
2. Ficou bom o funcionamento da edição, criando um novo campo de input
3. Achei interessante também o contador de tarefas registradas, uma funcionalidade que não estava no projeto inicial, mas deixou mais robusto o  projeto. Desafio: ao invés de contar a length, conte cada vez que a tarefa for registrada, assim, quando o/a usuário/usuária deletar, o número não diminui.
4. Faltou uma pequena margem (ex.: 10 px) entre os botões editar/deletar e cancelar/salvar

**Comment by karinafukuda** [comment]
Resolvida
